# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2ac148895d80d83288fccd62367b5379a9c448723bf1d8058828f0123afc728470f393a63bec14519f8bd137b835966ca8b663dba4003af592aba5deffed7d62

test:
  secret_key_base: f9916ea5c8d42e265cd1d10607256c897fff59fcb3968d0cd83229b5488b160ff8899373c4e3ec28905fb83c769408e3881737992ce3f8c67e3cddb61523967b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
